vcs: git

version-generator:
    name: semantic
    allow-label: true

version-persister: vcs-tag

prerequisites:
    working-copy-check: ~
    display-last-changes: ~

pre-release-actions:
    update-version-class:
        class: package.json
    command:
        cmd: node node_modules/gulp/bin/gulp.js babel
    vcs-commit: ~

post-release-actions:
    vcs-publish: ~
