build: false
platform: x86
clone_folder: c:\projects\puli\pulijs

cache:
  - node_modules

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "iojs"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "5.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
